### ISSUE TITLE
Initiative rolling not functional in Combat Tracker

### ISSUE THREAD

**Issue by XcaliburNick** [moo-man/AoS-Soulbound-FoundryVTT#1]
"So far, the biggest problem I have is that tokens added to an encounter don't roll their initiative when clicking on the roll initiative button. I think this is a .7.8 problem, as the option to either use initiative RAW, or Initiative +1d6 or +2d6 has been removed."

1. Open Combat Tracker
2. Add tokens to Encounter
3. Select "Roll Initiative" button for any character 
Bug: Roll button non functional

![image](https://user-images.githubusercontent.com/76702283/103235331-bcb40080-48f6-11eb-8a53-839553d4e9ba.png)

**Source:** Copied from Age of Soulbound Discord chat https://discord.com/channels/658075953590697984/788867933978755123/790528401286889473

**Comment by Vendare** [comment]
Fixed in Version 2.4.0
