### ISSUE TITLE
Multiple tokens from one actor - add counter to token names

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#105]
example: We have actor Grot. I need 3 tokens from that actor, so quick drag&drop and I have them. But the problem is that all three tokens have the same name - Grot. Maybe it is possible to check if that name already exist as a token in scene and if yes then add a counter to a new one. So for my example there will be tokens Grot, Grot1, Grot2.
In this system it is normal to have more then one token from one actor in scene ;/.

**Comment by moo-man** [comment]
This would be better suited as a module, for example, Token Mold

**Comment by Kasyks** [comment]
Thx I will check

**Comment by Kasyks** [comment]
Perfect :D
