### ISSUE TITLE
Not able to dismiss/close Soulfire/Doom pop-up.

### ISSUE THREAD

**Issue by Matt-Ceb** [moo-man/AoS-Soulbound-FoundryVTT#106]
A player of mine is playing a smaller laptop,and she'd like to close/dismiss the Soulfire/Doom pop-up. But there doesn't seem to be an option to do so.

**Comment by moo-man** [comment]
![image](https://user-images.githubusercontent.com/28637157/147160013-1fb9d166-ea23-46c4-b78e-2fb3f82c6774.png)
She can disable it in the system settings
