### ISSUE TITLE
Players can't see Items, Journal etc.

### ISSUE THREAD

**Issue by Matt-Ceb** [moo-man/AoS-Soulbound-FoundryVTT#107]
I purchased the core module, but no matter which permissions I give my players, they are not able to see the rules, spells and such. I've set them as owners and re-started Foundry a few times, but those remain invisible ot them. (Foundry, rules and core set on their most current iterations as of writing this report and I updated Foundry to 0.9 by uninstalling and installing it from a new insaller.)

**Comment by moo-man** [comment]
If you set the permissions via the folder, note that it only applies to documents that are immediate children of the folder, the permissions are not recursively applied to subfolders. Regardless, this is a core foundry level operation and not related to the system.
