### ISSUE TITLE
[develop] cant edit trait in weapons/armour already assigned to actors

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#108]
I have a actors which were created before I use this develop branch. So they have already weapon and armour assigned and I cant edit trait in that items.
![image](https://user-images.githubusercontent.com/88081888/148122714-ba62308b-9f56-465b-882d-28958087687b.png)

I can edit trait in already created weapons/armours without problem in item inventory.
I can edit trait in weapon/armour which I assigned to actors when running on develop branch.

**Comment by moo-man** [comment]
I can't reproduce, can you provide the actor json?
