### ISSUE TITLE
Overcast effects - Aetheric Armour

### ISSUE THREAD

**Issue by Matt-Ceb** [moo-man/AoS-Soulbound-FoundryVTT#124]
Hey, maybe I'm dumb, but I can't seem to be able to apply neither the upgraded armour bonus nor the duration of the overcast for Aetheric Armour.

I tried using data.combat.armour.bonus for the bonus, as 2:1 with an initial value of NULL and 1, and both times it didn't matter how many overcats were put into it, it always only applied one armour.

I then used duration.value for, well, the duration. It seemed to identify being used, as it greyed out the "initial" field. But, again: No matter how many overcats were put into it, the effect was showing only a one turn duration when I checked it.

I'm using the 4.3.0 module with the official package purchased and installed (1.1.0) and Foundry 9(249).

Edit: Is there an easier way to check what keys exist than to check the Token bar display? I haven't found one yet. (No, I don't have too much experience with how Foundry does those things, so I might be missing something super obvious!)

**Comment by moo-man** [comment]
So it should already be configured for you, are you saying the item provided is not working?

**Comment by Matt-Ceb** [comment]
There are no overcasts defined in the items that came with the paid module.

They look like this:

![image](https://user-images.githubusercontent.com/10468772/154108928-89dcaed8-8f62-469f-a623-83bc127dfe95.png)


Do I have to re-import the entries?

**Comment by moo-man** [comment]
Yes, or use the module content updater
