### ISSUE TITLE
Ambidextrous missing effect dialog description

### ISSUE THREAD

**Issue by Matt-Ceb** [moo-man/AoS-Soulbound-FoundryVTT#139]
See here:

https://i.imgur.com/WWeFw0j.png

FVTT V9.268
AoS:Soulbound v4.4.1
All other modules besides AoS und AoS Core disabled.

One step already taken:
I deleted all Core content, re-started the world, initialized the module anew and it still happens.

Foundry Language is set to English.

**Comment by moo-man** [comment]
The change descriptions are shown, not effect labels

**Comment by Matt-Ceb** [comment]
What does this even mean? Seriously?

Or, rather: How do I get the name of the talent to show up in the combat view? I know that it somehow works with Forbidden Knowledge when casting spells, but it would be nice tp have anything but an empty line and a random sentence as the name/label/whatever.

**Comment by moo-man** [comment]
It means there's no inherent connection between the label and the dialog description. Dialog descriptions are configured per-change. 

Perhaps I'm confused as to why you highlighted hunter, as it's working properly. The only issue is that Ambidextrous is missing its description.

**Comment by Matt-Ceb** [comment]
I think I explained that weirdly. Sorry.

The problem here isn't the description. Ambidextrous and Hunter both HAVE descriptions. 

The problem is the box you get when you want to make an attack and then have to chose which talents are applicable. For Double Weilding, "Ambidextrous" should be selected. But instead of "Ambidextrous" there's jus an empty line. And instead of "Hunter" there's this half-sentence instead of just "Hunter".

I assumed that the name of the talent/effect should be displayed in that list, as this is how it works with "Forbidden Knowledge". (i.e. It shows up as "Forbidden Knowledge")

**Comment by moo-man** [comment]
When I say description I don't mean the item description, each change in an effect is configured with a description to show in the roll dialog. The half sentence of hunter is what is configured for that Talent. However, the tooltip of the dialog change will show the originating Effect.

I generally don't just want to show the talent's name, as it usually doesn't give any indication on when / why it should be used. That's the point of the change description, give a clue on when it should be used in the Roll Dialog.

What it should probably do is show the Effect name if the description is blank, as is this case.

**Comment by Matt-Ceb** [comment]
Ah! That makes sense. Thank you for the explanation! :)

Is there a way for me to inject said description myself in the interim? (I'm comfortable editing JSON files and such. Not totally IT-illiterate. ;) )

**Comment by moo-man** [comment]
In the effect config -> effect tab -> there should be a cog button next to the trash can for each change (well, only Roll Dialog changes). That will pull up another window where you configure the description and the automatic activation. The description is just text, the automatic activation is pure JavaScript, but you can leave it blank and leave it manual.

**Comment by moo-man** [comment]
Now that I'm at my computer here's a screenshot: 
![image](https://user-images.githubusercontent.com/28637157/164060273-010e99cd-0ba1-4413-bc40-afb8f2edf214.png)

**Comment by Matt-Ceb** [comment]
Thank you, that worked perfectly! :)

**Comment by moo-man** [comment]
I reopened and changed the title to reflect an actual thing to fix, so I'll keep it open to remind me.
