### ISSUE TITLE
[Soulbound Core Module] The Great Parch map is black

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#158]
The map of The Great Parch is completely black with only map pins visible.

Error in console: "GET http://localhost:30000/modules/soulbound-core/assets/maps/the-great-parch-unlabeled.webp net::ERR_FAILED 304 (OK)"<br/>**From**: phenomen#1337<br/>age-of-sigmar-soulbound: 5.0.1

**Comment by phenomen** [comment]
![Foundry_Virtual_Tabletop_GH1Jl6c48Y](https://user-images.githubusercontent.com/138311/191395575-190fcf5f-f2f8-44ab-8ce2-bae8162771ef.png)

**Comment by moo-man** [comment]
Does the map exist in your files and does the scene have the correct path?

**Comment by phenomen** [comment]
Yes, it exists and I can even open the image file by pasting the URL into browser. But in Foundry it's always black. I've restarted the app, reimported scene, nothing helps.

**Comment by moo-man** [comment]
Well, I can't reproduce it, this is definitely a problem local to your setup. Is there anything noteworthy about your Foundry hosting?

**Comment by phenomen** [comment]
Can be closed, I fixed the issue by purging `%appdata%\Foundry Virtual Tabletop`
