### ISSUE TITLE
[Soulbound Core Module] Healing Spirit

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#171]
when I try to cast the Healing Spirit blessing, the roll is not performed, only a message is displayed in the chat.<br/>**From**: Darkwood#2281<br/>age-of-sigmar-soulbound: 5.1.1<br/>Active Modules: dice-so-nice

**Comment by StormDarkwood** [comment]
![imagen](https://user-images.githubusercontent.com/75157840/208255989-44f289fd-9bb5-49cc-a6cb-4553d382278d.png)

**Comment by StormDarkwood** [comment]
I have redone the character and now it works. sorry to have bothered you.
