### ISSUE TITLE
[Soulbound System] Can't import data on a scene

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#174]
I'm trying to import data on a scene from Dungeon Alchemist but I get an error:

Uncaught (in promise) ReferenceError: prototypeToken is not defined
    at Scene.SoulboundImportFromJson [as importFromJSON] (age-of-sigmar-soulbound.js:5855:9)
    at foundry.js:13764:68

I've tried to import the same data in other world with other system and it works fine.<br/>**From**: Thystra #7318<br/>age-of-sigmar-soulbound: 5.1.1<br/>Active Modules: JB2A_DnD5e, ambientdoors, autoanimations, autorotate, avclient-livekit, colorsettings, dae, dice-so-nice, dlopen, drag-ruler, dramatic-rolls, forge-compendium-browser, fxmaster, lib-wrapper, playlist_import, sequencer, socketlib, storyteller, tabletop-rpg-music, token-frames, vtta-tokenizer, vueport, forge-vtt, forge-vtt-optional

**Comment by moonbiter1** [comment]
I have the same behaviour. As a workaround for the moment, you can export in Dungeon Alchemist using the  "Universal VTT" format and use the foundry module "Universal Battlemap Importer" to load the scene.
