### ISSUE TITLE
[Soulbound System] Map stuck while loading

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#176]
I updated Foundry to version 11 and maps are not loading anymore. It always get stuck at 62% and I can't change to any other map because it says: "You cannot switch Scenes until resources finish loading for current view". I tried running the game in Safe mode but the same issue occurs.<br/>**From**: mathsteck@gmail.com<br/>age-of-sigmar-soulbound: 5.2.3<br/>Active Modules:

**Comment by mathsteck** [comment]
The current status of the scene:

![image](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/assets/3390366/d987b8b5-a2be-45d3-bd61-1008a2a48288)

This is affecting all scenes. Also, it is not possible to create a new one. It creates a blank scene (even when loading images) and the window get stuck in the process as well.

**Comment by mathsteck** [comment]
Here's the log:

[FoundryVTT.txt](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/files/11589753/FoundryVTT.txt)

**Comment by mathsteck** [comment]
Looks like this bug can be closed. It was fixed in the latest version.

**Comment by moo-man** [comment]
Fixed in https://github.com/moo-man/AoS-Soulbound-FoundryVTT/commit/1af21cb8e2854b97b6a32d92b7ff1ea55ca0ba0d
