### ISSUE TITLE
[Soulbound System] Unable to add items to Archetypes as a player

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#187]
cannot add items or talents to archetypes, dragging and dropping them onto the archetype item sheet does nothing and there doesn't seem to be another way to do it.<br/>**From**: innuendofountain<br/>age-of-sigmar-soulbound: 6.1.0<br/>Active Modules:

**Comment by InnuendoFountain** [comment]
Additional information, i have found that it works fine with GM permissions but not with just the create items permission, unsure if this is intended or not but makes it frustrating for me to import my own content into another players games.
