### ISSUE TITLE
Initiative value not updating in Combat Tracker from Character Sheets

### ISSUE THREAD

**Issue by XcaliburNick** [moo-man/AoS-Soulbound-FoundryVTT#2]
When using the Combat Tracker, tokens linked to Actors with Character Sheets don't populate with base or fixed Initiative values.

1. Open Combat Tracker
2. Add a Token linked to a Character Sheet actor that has an Initiative value set
Bug: All base initiative values are set to 0

![image](https://user-images.githubusercontent.com/76702283/103235907-208af900-48f8-11eb-8622-965ddb780a30.png)

Note: This may be a knock-on of https://github.com/moo-man/AoS-Soulbound-FoundryVTT/issues/1 as the basic system is not functional currently.

**Comment by Vendare** [comment]
This doesn't work because the initiative setting is not correctly registered so the gamesystem doesn't know how to handle initiative for combat.

**Comment by Vendare** [comment]
Fixed in Version 2.4.0
