### ISSUE TITLE
[UI] Focus apply 

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#22]
Now focus is applied only to maximize the amount of success. But there are many situation where you need 6 on die to activate (like talent crushing blow) or as much 6 as you can(like weapon trait REND or Cleave or talent Piece Armour). or 6 is counting as 2 damage and other thing were you need "6" on die. I suppose the best solution will be add it to roll popup window as checkbox like there is now for double training/focus as "one 6" and "Max 6". 
Other solution for this is showing in chat window with roll results information how much focus was added. with this information you can easily move focus to other die "in your head" to have a wanted "6". 

It also can be done by link talents, traits end other with specific roll but checkboxes are more universal solution.

Request: add two checkbox to all roll popup windows where focus can be applied. you cant mark both checkbox for amount of 6 in the same time so when you try mark second one the first one should unmark or second one is disabled until first remain marked.
"One 6" - we need one "6" on die so if we have it(by natural roll or by adding focus) remaining focus is used to maximize the amount of success.
"Max 6" - the amount of success is not important, we want to as much "6" on die as amount of focus allow. 
![obraz](https://user-images.githubusercontent.com/88081888/127300152-3f2067de-81c5-41ab-88d7-c961693187a4.png)

AND/OR
show in chat window with roll results how much focus was applied to this dice. 
 
![obraz](https://user-images.githubusercontent.com/88081888/127299559-391e3e26-5e8a-4d37-8eeb-9cb1c7936137.png)

**Comment by Vendare** [comment]
The plan is to make the fokus function to prioritize success first once no more success can be achieved to priotize 6s. The tricky bit is doing so effiently

**Comment by Kasyks** [comment]
So maybe take a simplest and most flexible way and allow to do it manually after the roll and before send to chat(and other automatic actions). Focus is specific in this system because allow player to have a little control over the dice result and manipulate it according to what they need (6s, more 6s, success or maybe both). It will not take a lot of time to apply focus to dices.

It should be added to every roll. Below roll button can be organize space for it.
- if no focus or all results on dices are 6s then roll button will work like now.
- if there is a focus then display: available focus(dynamically changed when focus applied), DN(must be displayed here because for example in combat roll it is not displayed ), successes(current dynamically calculated when focus added) and dices below roll button,  and by click on them you can add 1 focus (dice value will be changed after each click), you cant add to 6s, you cant take back already added focus. I dont know if it is possible here so it can be added "+" button over dice. Not all focus point must be used. When finished click "Finished" then results will send to chat and apply to other mechanisms 

![obraz](https://user-images.githubusercontent.com/88081888/127922110-78685628-a72e-43f9-9394-6a22a487e384.png)

**Comment by Kasyks** [comment]
As I see now focus can be applied manually only and it working very good beside that I cant  apply more then 1 focus to one dice. Selected dice increase by 1 after "apply focus" and I cant select any dice anymore even when I still have focus to spend and the description is changed to "3 applied" when I used only 1 focus point to increase 1 dice.

Solution1(fast) for apply more then 1 focus to one dice.
Every time when dice is left-clicked it automatically show new yellow value, (so you can click it multiple time until you still have focus to spend). Of course you can also click other dices. When all focus will be applied then you can use "apply focus".

Solution2(slow) for apply more then 1 focus to one dice.
When you select the dice then "apply focus". When you still have focus click the same dice and "apply focus", etc.

**Comment by moo-man** [comment]
I didn't realize you can apply more than one focus too a die, I think I'm going to go with clicking on a die multiple times, a small counter showing how much focus on each die.
