### ISSUE TITLE
Manual change attacker melee/accuracy during attacker attack roll

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#26]
There are talents (like BLOOD FRENZY or PATIENT STRIKE or BATTLE RAGE) , spells etc. which increase attacker melee/accuracy by "X" step usually for 1 round. But there is no possibility to do it quick during a combat roll. We can only manipulate target defence.  

Proposition: add additional field with attacker melee or accuracy (which can be changed for this roll like for defence) for a weapon roll which will be determined by skill chosen in roll window. Melee/accuracy label and value have to be dynamically changed when skill in roll windows is changed(as example for axe which is a melee weapon but you can throw it ) 
ballistic skill -> Attacker accuracy
weapon skill -> Attacker melee
![obraz](https://user-images.githubusercontent.com/88081888/127751554-fb627256-51a5-4d11-9525-2a80f363c4f7.png)

**Comment by Vendare** [comment]
The drop down is enabled you can increase it right there if you want to

**Comment by moo-man** [comment]
So the only issue I have with your mockup is that once you've changed the Attacker Melee/Accuracy, it becomes decoupled from the Attribute/Skill selection and could cause confusion on what exactly is being rolled.

How is this (not final, just to get the idea across)? Simply add or subtract number of steps

![image](https://user-images.githubusercontent.com/28637157/127922919-a694759b-3830-406f-b69a-691f5ef7078c.png)

**Comment by Kasyks** [comment]
moo-man your proposition is very good :). but I think it will be better to do "bonus" steps as drop list from -5 to +5 with default value 0 - there will be less confuse how to use it and steps have range 1-6. And the system have to lookup to not drop below 1(poor) step or above 6(extraordinary) step. And it should be "active" only for weapon skill and ballistic skill I suppose.

**Comment by moo-man** [comment]
So like this?
![image](https://user-images.githubusercontent.com/28637157/127925379-3bf1a9d2-ab15-4999-b142-71cc7bf75d6a.png)

**Comment by Vendare** [comment]
That looks terrible. The Ladder already has only 6 possible Values. The Dialog should always start at current Rating and be changeable to anything the user wants. The same mechanic used for the target defense drop down. People should be able to determine that a one step increase would mean that their current Good (3) goes to Great (4) and vice versa. That also elivates the need for check if someone has gone to high or too low

**Comment by moo-man** [comment]
I think I agree, considering attribute + skill selection on the dialog doesn't contribute to the Ladder Rating like I previously thought. So we're back at the image provided in the OP, which I think is fine.

**Comment by Kasyks** [comment]
moo-man I tested your changes and this is what I requested, thank you :)

**Comment by moo-man** [comment]
Thanks for testing them out!
