### ISSUE TITLE
[Branch UI] Chatcards need some kind of outline to be distinguishable

### ISSUE THREAD

**Issue by Vendare** [moo-man/AoS-Soulbound-FoundryVTT#38]
Right now old Messages appear as a wall of text :
![image](https://user-images.githubusercontent.com/6638899/129255782-f5450e4d-28be-4f42-bc69-7784261a63e4.png)

They really need more definition compared to the old style :
![image](https://user-images.githubusercontent.com/6638899/129256576-a208c87e-bbcf-4ce0-a7d6-0b5fc936e230.png)

The new ones lessen this problem by having a box around the content though. The Dice also loose some of their charm by not using the hammer of  sigmar symbol for the Six on the dice

**Comment by moo-man** [comment]
I'm not too concerned about the look of old chat card messages. The old dice images will definitely be brought back though.
