### ISSUE TITLE
Automatically calculate DN for attack based on enemy Defence

### ISSUE THREAD

**Issue by XcaliburNick** [moo-man/AoS-Soulbound-FoundryVTT#4]
"...an easier input for determining DN of an attack. Something like entering the defense of an enemy which then calculates the DN based on the player's Melee or Accuracy would also save time."

Source: Age of Soulbound Discord https://discord.com/channels/658075953590697984/788867933978755123/790528401286889473

**Comment by Vendare** [comment]
The system already does this if you use the target function of foundry though for melee it doesn't work correctly since it falsely uses accuracy

**Comment by Vendare** [comment]
Implemented in Version 2.4.0
