### ISSUE TITLE
Items - active aetheric devices item always show as weapon in combat tab

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#44]
there are devices which have to be active but should not be added to combat tam as a weapon.
example
Basic aether-rig - active add 6 energy(capacity) but it is also appear in combat tab as a weapon because we always have to choose category melee or accuracy. 

I dont know how it is connected but maybe it will be enough to add third category - NONE. and devices witch category NONE will not show as weapon.

**Comment by Vendare** [comment]
An Aetheric Device will always be listed as an Attack as long as the Damage field retains any sort of value. The Damage field in  the item needs to remain empty. This is certainly not ideal. The category should be changed to include a device or gear option. So the Device is only included if the category is set to either Melee or Ranged Weapon

https://user-images.githubusercontent.com/6638899/129463234-8603bebd-d34f-40a3-a256-6dd296f64723.mp4

**Comment by Kasyks** [comment]
I always input "-" in unused fields to make sure that I didn't miss any field by mistake. I will leave this damage filed empty then. Thx :)

**Comment by moo-man** [comment]
This seems to be fixed in the UI branch, devices only show if they define damage
