### ISSUE TITLE
weapon bonus - apply only when used to attack 

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#49]
Now bonuses are applied always when item is active. And this is ok for items. But there are abilities which give character static step  bonus to melee/accuracy/defense and/or static bonus dices when character make an specific attack, for example character which fight dual weapons will have AMBIDEXTROUS-always will have 1 bonus dice and RELENTLESS ASSAULT - always will have melee +1 step. 

Have it you can create 2 weapons , one when you use dual, and second when a single weapon is used. We will have a flexibility. This will be much easier then change each time melee and input bonus dice value. 
I know that now item can be activated/deactivated but in my opinion it is unnecessary clicking/checking and the bonus dice cant be now added to item.

Maybe solution will be add second bonus tab (Attack bonus) with 
attributes(body,mind,soul)
abilities(melee,accuracy.defense)
bonus dice

or just add checkbox to current bonus tab which will mark that this bonus will be applied only when used to attack (bonus dice have to be added to this tab).

**Comment by moo-man** [comment]
The bonus tab is going to be removed so I'm not sure how these suggestions will fit in

**Comment by moo-man** [comment]
This should be resolved with the effects tab in the roll dialog
