### ISSUE TITLE
Success values don't have a method of applying Focus values

### ISSUE THREAD

**Issue by XcaliburNick** [moo-man/AoS-Soulbound-FoundryVTT#5]
Rolling against a DN with a Focus value doesn't apply the Focus rating to the successes, and doesn't allow any manual way of doing so to modify the result.

Request: When the dice are rolled, if a player has a Focus rating, being able to select a Dice result and increase a D6 result up to the number of Focus available.

![image](https://user-images.githubusercontent.com/76702283/103236493-e7ec1f00-48f9-11eb-8658-f1b0d816eda6.png)

**Comment by moo-man** [comment]
Added in #21
