### ISSUE TITLE
[UI] cant make a roll

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#55]
player not able to make a test:(after roll button pressed window is closed but the is no results in chat, I set to have at least 1 dice in pool )
-weapon roll

NPC not able to make a test:(after roll button pressed window is closed but the is no results in chat, I set to have at least 1 dice in pool )
- weapon roll
- skill roll
- spell/miracle roll

**Comment by moo-man** [comment]
I cannot reproduce this, do you see any console errors?

**Comment by Kasyks** [comment]
player/npc weapon roll
![obraz](https://user-images.githubusercontent.com/88081888/133858422-6bcccb88-3fb0-411d-aadc-7be969042068.png)

skill and spell/miracle are working today...strange.

**Comment by moo-man** [comment]
Is this an old weapon before I changed how traits are added?

**Comment by Kasyks** [comment]
this is a new world with newest UI version. I attached items.db with one weapon created.
[items.db.txt](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/files/7190551/items.db.txt)
