### ISSUE TITLE
[UI] speed fields

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#56]
Missing fly speed field. Speed fields is no longer a drop list.

**Comment by moo-man** [comment]
I'm not sure how this is still an issue, I fixed this with ff3fcf836471f8f68c2e84f924d3f63970489ece

**Comment by Kasyks** [comment]
What can I say...I have this in npc/player sheet (combat tab)
![obraz](https://user-images.githubusercontent.com/88081888/133855726-5c0ad442-11c1-4f6b-99ac-9cb14acc7a9c.png)

**Comment by moo-man** [comment]
Click on Speed to configure it
