### ISSUE TITLE
[UI] Apply Rend to armour not working

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#60]
From the chat - right click option. I select the token and apply Rend from chat, damage is applied to token, Rend not.

**Comment by Vendare** [comment]
Was the armour Magical ? Rend isn't applied to armour with the magical trait.

**Comment by Kasyks** [comment]
weapon with rend, normal Armour without any trait
[items.db.txt](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/files/7227928/items.db.txt)
s

**Comment by moo-man** [comment]
Please try again with the fix

**Comment by Kasyks** [comment]
cant test this because sheet is totally broken. No error in console.
![obraz](https://user-images.githubusercontent.com/88081888/137551554-07ffa215-3fc8-45ea-9b4a-82dcde95ae49.png)

I changed to old version(below) and sheet is displayed correctly again. 
&& !i.traits.toLowerCase().includes(game.i18n.localize("TRAIT.MAGICAL")));

so there is something wrong with this
&& !i.traitList.magical

**Comment by Vendare** [comment]
> Rend is working now for non-magic Armour.
> 
> But there is another issue. System not recognize if weapon was magical/sigmarite (which should rend any physical armour). Also Sigmarite is not treated as magical(yes we can add sigmarite and magical to weapon/armour ;) ).
> 
> non-magic armour should be rend by normal/magic/sigmarite weapon magic armour should be rend only by magic/sigmarite weapon sigmarite armour should be rend only by magic/sigmarite weapon

RAW Rend only applies to non-magical armour

**Comment by Kasyks** [comment]
Not house rules but official information from core book and confirmed by C7 staff on discord. But you are code masters and we will have what you will implement.

in the last line (core book)
![obraz](https://user-images.githubusercontent.com/88081888/137598383-9bc5c254-7762-4d69-ad9f-e54f5e07814f.png)

and confirmation by C7 staff about magical armour.
![obraz](https://user-images.githubusercontent.com/88081888/137598413-7df453bb-2d21-481e-ba5e-ebfbbed17f75.png)
