### ISSUE TITLE
[UI] skill/spell/weapon tests - there is something wrong with success count and different focus allocation

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#63]
successes are counted wrongly and in the strange way :)

same skill in the same player. focus allocation in the first roll was manual, for second roll successes (I thing successes should be a default option). Nevertheless skill has no focus :).  
![obraz](https://user-images.githubusercontent.com/88081888/137556371-e6e20588-1fb1-4fcf-8282-ceede6c6c1bd.png)
![obraz](https://user-images.githubusercontent.com/88081888/137556424-59925091-1ba6-4fcd-9794-cd2247b4395e.png)

other skill (same way focus allocation as above)
![obraz](https://user-images.githubusercontent.com/88081888/137556883-713b5313-1e8b-4375-b347-f05adb40ab1a.png)
![obraz](https://user-images.githubusercontent.com/88081888/137556955-47ddac0a-c0c1-4a66-9f43-46240fb773b7.png)

Manual focus allocation has a bug/not ready for use yet?

**Comment by moo-man** [comment]
I believe this has been fixed with the focus refactor
