### ISSUE TITLE
[UI] Something is wrong in combat roll for player and NPC

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#68]
![obraz](https://user-images.githubusercontent.com/88081888/141332324-e1769d38-5cd1-4457-b762-6c26171c9b8b.png)

**Comment by moo-man** [comment]
Can you export the actor?

**Comment by Kasyks** [comment]
[actors.db.txt](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/files/7522592/actors.db.txt)
[items.db.txt](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/files/7522595/items.db.txt)

**Comment by moo-man** [comment]
Can you export just the actor in question please? I don't need the entire db file

**Comment by Kasyks** [comment]
[fvtt-Actor-npc.json.txt](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/files/7522638/fvtt-Actor-npc.json.txt)
[fvtt-Actor-player.json.txt](https://github.com/moo-man/AoS-Soulbound-FoundryVTT/files/7522639/fvtt-Actor-player.json.txt)

**Comment by moo-man** [comment]
I had not gotten to combat tests yet but it should be fixed now

**Comment by Kasyks** [comment]
It is fixed now.
