### ISSUE TITLE
Token's third stat value unclear / non functional

### ISSUE THREAD

**Issue by XcaliburNick** [moo-man/AoS-Soulbound-FoundryVTT#7]
When right clicking on a token, there is a third stat value that can be entered that doesn't appear to be functional. There is a small chevron attached to the field, but no context menu.

Bug: Updating this value has no functionality in either the Combat Tracker or the Character Sheet
Request: Add a tooltip to this icon

![image](https://user-images.githubusercontent.com/76702283/103238063-6a76dd80-48fe-11eb-80d5-5dcb41bb5b07.png)

**Comment by moo-man** [comment]
That is the token height indicator
