### ISSUE TITLE
[Soulbound System] Dual Wielding

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#74]
When dual wielding, a player needs to apportion their Training across two separate dice pools. At the moment this would require a player using the Bonus Dice field on the Test dialog box, but they would also need to reference the Stats page to see their total Training in the appropriate skill and then need to remember how much of that Training had been used on the first attack. They then need to make a second attack and use the Bonus Dice to reduce the pool again reflecting the amount of dice remaining from the Training. This is slightly more complicated if the dual wielder is using melee and ranged weapons. See page 148 or Core Rulebook. Would be nice for their be a way to select a dual wielding attack and have the dice pool splits sorted and both rolls made together. Then focus can be applied to either roll. Note that bonus dice from Talent, etc. are normally added before the split and not too each attack.<br/>**From**: TrickyDUK #3037<br/>age-of-sigmar-soulbound: 4.0.0<br/>soulbound-core: 1.0.0

**Comment by Vendare** [comment]
Important Focus applies only once for both Roles. So if someone uses all his focus on the mainhand attack he can't use any focus on the off-hand attack and vice versa.

**Comment by Tricky110974** [comment]
> Important Focus applies only once for both Roles. So if someone uses all his focus on the mainhand attack he can't use any focus on the off-hand attack and vice versa.

This is why I think that dual-wielding needs to be handled a function. Maybe a check box that determines which weapons are being dual-wielded and then when you click either, the dialog box brings back both weapons and allows you to split the dice pool. After the roll, the chat box shows the results of both and allows the allocation of Focus from the single pool. This gets more complicated when there are melee and ranged attacks as you need to pick the primary weapon (which could be the weapon that you click to initiate the attack) so Training and Focus can be properly applied.

**Comment by Kasyks** [comment]
And remember that target can be single for both attacks and  can be splited to two targets, where each can have different Defence.
