### ISSUE TITLE
Token Bar2 Resource non functional when set to combat.health.wounds

### ISSUE THREAD

**Issue by XcaliburNick** [moo-man/AoS-Soulbound-FoundryVTT#8]
By default, a token uses combat.health.wounds as the Bar2 Resource. This does not currently functionally link to the Character Sheet, nor retain a value when entered in the Token status field.

1. Right Click on a token that has a Character Sheet link
2. Enter any number into the top (blue) Bar2 field and press 'enter'
3. Right click on the token again and/or open the Character Sheet and view 'Wounds' stat

Bug: The value is not stored OR updated in the character sheet

**Comment by moo-man** [comment]
This is because wounds are calculated by the amount of "Wound Items" the actor has, instead of just a numeric stored value.
