### ISSUE TITLE
[Soulbound system] Test fields purpose in spell/miracle item card

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#94]
Is it only informational when opposed test is required? If yes then it will be good to have this info in chat after cast.

spell
![image](https://user-images.githubusercontent.com/88081888/145692319-b12179b5-d599-4661-97c3-a1f5b8129e1f.png)

miracle (opossed checkbox nothing change - there is always soul+devotion)
![image](https://user-images.githubusercontent.com/88081888/145692380-4b51c274-04a0-41b8-8a56-f06ba1ec139b.png)

**Comment by moo-man** [comment]
This info *is* in chat after you cast, or I'm not understanding the issue.

**Comment by Kasyks** [comment]
Miracle first:
1. Opossed marked ( I dont even know if this is a miracle cast because there is only information about test)
![image](https://user-images.githubusercontent.com/88081888/145692652-2e87e0ca-f23e-4531-aec5-0b91eb517ffa.png)
2. Opossed not marked (only miracle name)
![image](https://user-images.githubusercontent.com/88081888/145692672-a1ab8dfe-41a3-4039-a1d1-1b586b3fd3cc.png)

spell
![image](https://user-images.githubusercontent.com/88081888/145692699-9a352e42-1069-4f76-9f48-add822229289.png)

**Comment by moo-man** [comment]
You need to set the DN for it to show up

**Comment by Kasyks** [comment]
Yes you have right (I think it is time to go sleep ;) ). It will be more intuitive when DN will be above field not in the field, like for the rest of fields.

**Comment by moo-man** [comment]
I'm not sure I understand what you're saying.

Also the field is pretty plainly there. I'm not sure how it could be more clear.

**Comment by Kasyks** [comment]
![image](https://user-images.githubusercontent.com/88081888/145692993-33517bd6-4a34-4524-bd55-a0aa7b849a34.png)

So it will be similar to 

![image](https://user-images.githubusercontent.com/88081888/145693015-b348c7cf-17b9-485b-83e5-f240949cb3bf.png)

**Comment by moo-man** [comment]
Oh, they're quite different purpose, the top DN is required, the bottom DN is optional. I'm going to close this as the original issue is resolved, but if people have trouble realizing what the secondary DN is for then I can address it.
