### ISSUE TITLE
[Soulbound Core Module] Great Crossbow is listed under Melee Weapons

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#97]
The Great Crossbow weapon is listed under the Melee Weapons section of the rulebook, with melee stats.

1. Open Journal Entries > Core Rulebook > Equipment > Weapons and Armour.
2. Scroll down to Melee Weapons
3. Note that Great Crossbow is listed
4. Click on Great Crossbow
5. Note that type is set as Melee and icon is the axe (instead of bow)<br/>**From**: MadDave123#3059<br/>age-of-sigmar-soulbound: 4.0.1<br/>soulbound-core: 1.0.0

**Comment by moo-man** [comment]
Update your core module

**Comment by MadDave123** [comment]
Core module updated to 1.0.1. The bug still occurs.
